Feature/169 metadata support
mariadb-operator/mariadb-operator pull request #175
Opened 2023-07-29 11:05 UTC by vavrajosef

Closes issue #169

2023-07-29 12:12 UTC, mmontes11 requested changes
Thanks for your contribution, a couple of things:
- We need to add the `metadata` field to the `volumeClaimTemplates`, which is the main purpose of this feature. I've added a commit suggestion for that
- Run `make gen` to generate code and CRDs.  The CI is failing because of this
- To run test locally:
```bash
make cluster
make install
make net
make test
```

Let me know if you have any question!

2023-07-29 12:12 UTC, mmontes11 commented on pkg/builder/statefulset_builder.go
> +			Spec: mariadb.Galera().VolumeClaimTemplate.Spec,
```suggestion
func buildStsVolumeClaimTemplates(mariadb *mariadbv1alpha1.MariaDB) []corev1.PersistentVolumeClaim {
	vctpl := mariadb.Spec.VolumeClaimTemplate
	vctpl.ObjectMeta.Name = StorageVolume
	pvcs := []corev1.PersistentVolumeClaim{
		vctpl,
	}
	if mariadb.Galera().Enabled {
		galeraVctpl := *mariadb.Galera().VolumeClaimTemplate
		galeraVctpl.ObjectMeta.Name = galeraresources.GaleraConfigVolume
		pvcs = append(pvcs, galeraVctpl)
	}
	return pvcs
}
```

2023-07-29 12:15 UTC, mmontes11 requested changes

2023-07-29 12:15 UTC, mmontes11 commented on pkg/builder/statefulset_builder.go
> +			Spec: mariadb.Galera().VolumeClaimTemplate.Spec,
can we do something like this?:

```golang
func buildStsVolumeClaimTemplates(mariadb *mariadbv1alpha1.MariaDB) []corev1.PersistentVolumeClaim {
	vctpl := mariadb.Spec.VolumeClaimTemplate
	vctpl.ObjectMeta.Name = StorageVolume
	pvcs := []corev1.PersistentVolumeClaim{
		vctpl,
	}
	if mariadb.Galera().Enabled {
		galeraVctpl := *mariadb.Galera().VolumeClaimTemplate
		galeraVctpl.ObjectMeta.Name = galeraresources.GaleraConfigVolume
		pvcs = append(pvcs, galeraVctpl)
	}
	return pvcs
}
```

2023-08-02 20:10 UTC, vavrajosef commented on pkg/builder/statefulset_builder.go
> +			Spec: mariadb.Galera().VolumeClaimTemplate.Spec,
I have applied this suggestion.

2023-08-02 20:10 UTC, vavrajosef commented
Thanks for looking into this and thanks for the feedback. I have updated the PR. Please let me know if this is what you had in mind.

2023-08-03 10:38 UTC, mmontes11 commented
Hey @vavrajosef ! thanks for your changes, they look fine!

However, I've just realized that the [issue](https://github.com/mariadb-operator/mariadb-operator/issues/169) definition implies breaking changes in the CRDs, something we want to avoid whenever possible. What I would suggest is defining our own `VolumeClaimTemplate` type embedding the `corev1.PersistentVolumeClaimSpec ` and adding annotations and labels, which is the main purpose of this issue. It would be something like:

```golang
type VolumeClaimTemplate struct {
    corev1.PersistentVolumeClaimSpec 
    Labels      map[string]string `json:"labels,omitempty"`
    Annotations map[string]string `json:"annotations,omitempty"`
}
``` 
This way, the existing `MariaDB` definitions in our users clusters are still valid and no changes from their side are needed to upgrade.

Sorry for misguiding you! I will be picking your changes to another branch and adding you as a co-author.

2023-08-03 15:25 UTC, mmontes11 commented
Closed in favor of:

https://github.com/mariadb-operator/mariadb-operator/pull/185

Thanks for your contribution @vavrajosef

2023-08-03 15:25 UTC, closed without merging