[feature]support configurable type and annotations to MariaDB service
mariadb-operator/mariadb-operator pull request #70
Opened 2023-03-21 14:03 UTC by ksankeerth

Hi @mmontes11 

Please check this PR and let me know anything to be changed. I added modified changes of  generated files as well. I tested locally and it seems to be working.  Service is considered as optional. If we don't specify, I pass an empty struct to client. Since K8s default is ClusterIP, it'll create a service with ClusterIP.  

Fixes #46 

Thanks,
Sankeerthan

2023-03-21 19:29 UTC, mmontes11 requested changes
Hey @ksankeerth ! thanks a lot for your contribution ❤️ 🙇🏻 

The changes LGTM 🚀 , left a suggestion, could you take a look?

Could you also please add some test cases?:
- Specify a `Service` [here](https://github.com/mariadb-operator/mariadb-operator/blob/main/controllers/suite_test_data.go#L134) to make sure it reconciles properly
- Add a case [here](https://github.com/mariadb-operator/mariadb-operator/blob/main/api/v1alpha1/mariadb_webhook_test.go#L313) to test that the `Service` is mutable

2023-03-24 02:35 UTC, ksankeerth commented on api/v1alpha1/mariadb_types.go
> +type MariaDBService struct {
+1. done the changes.

2023-03-24 02:35 UTC, ksankeerth commented
> Hey @ksankeerth ! thanks a lot for your contribution ❤️ 🙇🏻
> 
> The changes LGTM 🚀 , left a suggestion, could you please take a look?
> 
> Could you also please add some test cases?:
> 
> * Specify a `Service` [here](https://github.com/mariadb-operator/mariadb-operator/blob/main/controllers/suite_test_data.go#L134) to make sure it reconciles properly
> * Add a case [here](https://github.com/mariadb-operator/mariadb-operator/blob/main/api/v1alpha1/mariadb_webhook_test.go#L313) to test that the `Service` is mutable

@mmontes11  Thanks for  the review. I have done the changes requested. Please check when you have time.

2023-03-24 18:37 UTC, mmontes11 approved these changes
LGTM 🚀  Thanks for contributing to `mariadb-operator` 🦭 ❤️

2023-03-24 18:37 UTC, merged