Create docker.md
mariadb-operator/mariadb-operator pull request #808
Opened 2024-08-22 22:04 UTC by mariadb-pieterhumphrey

creating docker.md page to elaborate our docker images.   must be updated every release.

2024-08-22 22:05 UTC, mariadb-pieterhumphrey commented
@mariadb-mmontes for your review.  wasn't sure if exporter images were getting bumped in version for v0.0.30 so they are still v0.0.1

2024-08-23 09:22 UTC, mmontes11 requested changes
Hey there @mariadb-pieterhumphrey !

Exporters are still on `v0.0.1`, so we are good.

Left a couple of suggestions/improvements, Other than that Let'sGetThisMerged! 👍🏻

2024-08-23 09:22 UTC, mmontes11 commented on docs/docker.md
> +      <td><a href=ghcr.io/mariadb-operator/mariadb-operator>ghcr.io/mariadb-operator/mariadb-operator</a></td>
```suggestion
      <td><a href=https://github.com/mariadb-operator/mariadb-operator/pkgs/container/mariadb-operator>ghcr.io/mariadb-operator/mariadb-operator</a></td>
```
This links is broken

2024-08-23 09:22 UTC, mmontes11 commented on docs/docker.md
> +> **Note**: Using Docker images other than the supported ones in this document is not recommended at this time.
```suggestion
> [!NOTE]  
> Using Docker images other than the supported ones in this document is not recommended at this time.
```
Use GitHub enhanced markdown banner

2024-08-23 15:43 UTC, mariadb-pieterhumphrey commented on docs/docker.md
> +      <td><a href=https://hub.docker.com/_/mariadb/tags?page=&page_size=&ordering=&name=11.4.3-ubi9>docker.mariadb.com</a><br>Login required, click link for instructions</td>
docker.mariadb.com redirects to the main docs page in question, so it does

2024-08-23 16:38 UTC, mariadb-pieterhumphrey commented on docs/docker.md
> +      <td><a href=ghcr.io/mariadb-operator/mariadb-operator>ghcr.io/mariadb-operator/mariadb-operator</a></td>
thank you nice catch

2024-08-23 19:04 UTC, mariadb-pieterhumphrey commented on docs/docker.md
> +      <td><a href=https://hub.docker.com/_/mariadb/tags?page=&page_size=&ordering=&name=11.4.3-ubi9>docker.mariadb.com</a><br>Login required, click link for instructions</td>
oh, apologies I see what you mean.  yes, I should have had the ahref be docker.mariadb.com, not dockerhub

2024-08-27 09:13 UTC, mmontes11 approved these changes
LGTM! To save you the trouble of solving conflicts, I've added this docs to `release-v0.0.30` branch and added you as a co-author:
- https://github.com/mariadb-operator/mariadb-operator/blob/eafa45f81cd1777ddeff487bf4bb16ae54eec60e/docs/DOCKER.md

2024-08-27 09:14 UTC, mmontes11 commented
This has been added to `release-v0.0.30` branch:
- https://github.com/mariadb-operator/mariadb-operator/blob/release-v0.0.30/docs/DOCKER.md

Closing!

2024-08-27 09:14 UTC, closed without merging