Allow scaling to 0 to stop workloads
mariadb-operator/mariadb-operator pull request #829
Opened 2024-09-04 18:50 UTC by Jancis

Allows scaling to 0 to stop workloads. Works both ways, by scaling mariadb resource (`kubectl scale mdb`) and statefulset (`kubectl scale sts`) - changes are reflected to the related resource.

2024-09-05 09:08 UTC, mmontes11 requested changes
Hey there @Jancis ! Thanks a lot, this is a fantastic contribution, Seems like you are understanding the codebase very well despite this one being your first contribution, well done 🎖️ 

I've left some detailed comments that hopefully will serve you as guidance to cross the finish line, it looks promising. 

I also have some more asks for you if you don't mind:
- The same way we did with the `Suspended` state, please add an integration tests [here](https://github.com/mariadb-operator/mariadb-operator/blob/343405d3099fbf846862f4933ceccd12ee220cd8/internal/controller/mariadb_controller_test.go#L90) to prove that this feature works as intended.
- Whenever we upscale a Galera cluster, we could set the `GaleraNotReady` condition like we do [here](https://github.com/mariadb-operator/mariadb-operator/blob/343405d3099fbf846862f4933ceccd12ee220cd8/pkg/controller/galera/init.go#L51) to trigger the recovery process. I can do this myself if you feel like it is too complicated.

Thanks!

2024-10-03 18:51 UTC, Jancis commented
I implemented most of the changes (except tests, did not check them out yet), but I ran into issue that it tries runs reconciliation cycle on Downscaled (non-Ready) mariadb resources, causing frequent API calls.

2025-03-22 02:42 UTC, closed without merging

2025-06-29 19:53 UTC, pinpins commented
no plans to get it merged?

2025-06-30 08:20 UTC, Jancis commented
I lacked ability to make this work properly, it was making quite a bit of API queries while downscaled, to query state and I could not figure out the best approach; then I got pulled into other stuff and I dropped the mariadb-operator for a while.

I made the requested changes (Use "Downscaled" instead of "Stopped"; Don't reconcile statefulset) but never pushed it. Here they are, in case you are interested - https://github.com/mariadb-operator/mariadb-operator/compare/main...wunderio:mariadb-operator:feature/downscaling?expand=1

I made a custom operator that does the reconciliation of mariadb operator owned statefulsets back to mdb resource (that I had to [remove from the PR](https://github.com/mariadb-operator/mariadb-operator/commit/e4877980909333145f559c0986f00f1e101b877e#diff-7ca6f0c1644a79617a2178f139538d91af71f183a30e80a947dc4f5a04e1d185L57-L67)), but then i left that idea too, had to switch over to other stuff.