Fix: crash when SQLJob has unknown dependencies
mariadb-operator/mariadb-operator pull request #924
Opened 2024-10-07 17:44 UTC by am6737

Added error handling for unresolved dependencies to prevent the operator from crashing.

2024-10-07 17:51 UTC, am6737 commented
Hey @mmontes11

I have some questions, and I would like to hear your thoughts

1. **Should we iterate through all DependsOn items?**  
   Should we return immediately (on the first error) or iterate through all dependencies and return after checking all of them?

2. **Is it necessary to add a retry interval?**  
   Should we add `RequeueAfter`, or use the default retry mechanism?

3. **Should we directly return return false, ctrl.Result{}, nil without any retries?**

2024-10-09 10:10 UTC, mmontes11 commented
Hey there @am6737 ! 

> Should we iterate through all DependsOn items?

No, we can return whenever we find a non ready dependency.

> Is it necessary to add a retry interval?

Yes, I think it is valuable to let the user tune the retry interval i.e. linear customizable retry interval. Whenever the default exponential retry  is in advanced state, it can seem that the the `SqlJob` does not get reconciled, therefore I think a linear reconciliation customizable by the user is better in this case.

The source of inspiration is Flux's `retryInterval` and `interval` respectively:
- https://fluxcd.io/flux/components/kustomize/api/v1/
- https://fluxcd.io/flux/components/helm/api/v2/

> Should we directly return return false, ctrl.Result{}, nil without any retries?

I think this is not strictly related to the issue. See a fixed version of `waitForDependencies`:

```go
func (r *SqlJobReconciler) waitForDependencies(ctx context.Context, sqlJob *v1alpha1.SqlJob) (bool, ctrl.Result, error) {
	if sqlJob.Spec.DependsOn == nil {
		return true, ctrl.Result{}, nil
	}
	logger := log.FromContext(ctx)

	for _, dep := range sqlJob.Spec.DependsOn {
		sqlJobDep, err := r.RefResolver.SqlJob(ctx, &dep, sqlJob.Namespace)

		if err != nil {
			msg := fmt.Sprintf("Error getting SqlJob dependency: %v", err)
			if apierrors.IsNotFound(err) {
				msg = fmt.Sprintf("Dependency '%s' not found", dep.Name)
			}

			logger.Info(msg)
			return false, ctrl.Result{RequeueAfter: r.RequeueInterval}, r.patchStatus(ctx, sqlJob, r.ConditionComplete.PatcherFailed(msg))
		}
		if !sqlJobDep.IsComplete() {
			msg := fmt.Sprintf("Dependency '%s' not ready", dep.Name)

			logger.Info(msg)
			if err := r.patchStatus(ctx, sqlJob, r.ConditionComplete.PatcherFailed(msg)); err != nil {
				return false, ctrl.Result{}, err
			}
			return false, ctrl.Result{RequeueAfter: r.RequeueInterval}, nil
		}
	}
	return true, ctrl.Result{}, nil
}
``` 



I think it will be great to add an integration tests for this here to ensure that the `SqlJob` consistently reports non ready state whenever a non existing dependency is specified:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/internal/controller/sqljob_controller_test.go

2024-10-09 10:11 UTC, mmontes11 requested changes
Hey there @am6737 ! 

> Should we iterate through all DependsOn items?

No, we can return whenever we find a non ready dependency.

> Is it necessary to add a retry interval?

Yes, I think it is valuable to let the user tune the retry interval i.e. linear customizable retry interval. Whenever the default exponential retry  is in advanced state, it can seem that the the `SqlJob` does not get reconciled, therefore I think a linear reconciliation customizable by the user is better in this case.

The source of inspiration is Flux's `retryInterval` and `interval` respectively:
- https://fluxcd.io/flux/components/kustomize/api/v1/
- https://fluxcd.io/flux/components/helm/api/v2/

> Should we directly return return false, ctrl.Result{}, nil without any retries?

I think this is not strictly related to the issue. See a fixed version of `waitForDependencies`:

```go
func (r *SqlJobReconciler) waitForDependencies(ctx context.Context, sqlJob *v1alpha1.SqlJob) (bool, ctrl.Result, error) {
	if sqlJob.Spec.DependsOn == nil {
		return true, ctrl.Result{}, nil
	}
	logger := log.FromContext(ctx)

	for _, dep := range sqlJob.Spec.DependsOn {
		sqlJobDep, err := r.RefResolver.SqlJob(ctx, &dep, sqlJob.Namespace)

		if err != nil {
			msg := fmt.Sprintf("Error getting SqlJob dependency: %v", err)
			if apierrors.IsNotFound(err) {
				msg = fmt.Sprintf("Dependency '%s' not found", dep.Name)
			}

			logger.Info(msg)
			return false, ctrl.Result{RequeueAfter: r.RequeueInterval}, r.patchStatus(ctx, sqlJob, r.ConditionComplete.PatcherFailed(msg))
		}
		if !sqlJobDep.IsComplete() {
			msg := fmt.Sprintf("Dependency '%s' not ready", dep.Name)

			logger.Info(msg)
			if err := r.patchStatus(ctx, sqlJob, r.ConditionComplete.PatcherFailed(msg)); err != nil {
				return false, ctrl.Result{}, err
			}
			return false, ctrl.Result{RequeueAfter: r.RequeueInterval}, nil
		}
	}
	return true, ctrl.Result{}, nil
}
``` 



I think it will be great to add an integration tests for this here to ensure that the `SqlJob` consistently reports non ready state whenever a non existing dependency is specified:
- https://github.com/mariadb-operator/mariadb-operator/blob/main/internal/controller/sqljob_controller_test.go

2024-10-10 16:47 UTC, am6737 commented
> Hey there @am6737 !
> 
> > Should we iterate through all DependsOn items?
> 
> No, we can return whenever we find a non ready dependency.
> 
> > Is it necessary to add a retry interval?
> 
> Yes, I think it is valuable to let the user tune the retry interval i.e. linear customizable retry interval. Whenever the default exponential retry is in advanced state, it can seem that the the `SqlJob` does not get reconciled, therefore I think a linear reconciliation customizable by the user is better in this case.
> 
> The source of inspiration is Flux's `retryInterval` and `interval` respectively:
> 
> * https://fluxcd.io/flux/components/kustomize/api/v1/
> * https://fluxcd.io/flux/components/helm/api/v2/
> 
> > Should we directly return return false, ctrl.Result{}, nil without any retries?
> 
> I think this is not strictly related to the issue. See a fixed version of `waitForDependencies`:
> 
> ```go
> func (r *SqlJobReconciler) waitForDependencies(ctx context.Context, sqlJob *v1alpha1.SqlJob) (bool, ctrl.Result, error) {
> 	if sqlJob.Spec.DependsOn == nil {
> 		return true, ctrl.Result{}, nil
> 	}
> 	logger := log.FromContext(ctx)
> 
> 	for _, dep := range sqlJob.Spec.DependsOn {
> 		sqlJobDep, err := r.RefResolver.SqlJob(ctx, &dep, sqlJob.Namespace)
> 
> 		if err != nil {
> 			msg := fmt.Sprintf("Error getting SqlJob dependency: %v", err)
> 			if apierrors.IsNotFound(err) {
> 				msg = fmt.Sprintf("Dependency '%s' not found", dep.Name)
> 			}
> 
> 			logger.Info(msg)
> 			return false, ctrl.Result{RequeueAfter: r.RequeueInterval}, r.patchStatus(ctx, sqlJob, r.ConditionComplete.PatcherFailed(msg))
> 		}
> 		if !sqlJobDep.IsComplete() {
> 			msg := fmt.Sprintf("Dependency '%s' not ready", dep.Name)
> 
> 			logger.Info(msg)
> 			if err := r.patchStatus(ctx, sqlJob, r.ConditionComplete.PatcherFailed(msg)); err != nil {
> 				return false, ctrl.Result{}, err
> 			}
> 			return false, ctrl.Result{RequeueAfter: r.RequeueInterval}, nil
> 		}
> 	}
> 	return true, ctrl.Result{}, nil
> }
> ```
> 
> The problem is that whenever the `RefResolver` returns an `err`, `sqlJobDep` will always be nil, leading to a crash when calling `sqlJobDep.IsComplete`. The solution is returning inside the `err != nil` block.
> 
> I think it will be great to add an integration tests for this here to ensure that the `SqlJob` consistently reports non ready state whenever a non existing dependency is specified:
> 
> * https://github.com/mariadb-operator/mariadb-operator/blob/main/internal/controller/sqljob_controller_test.go

Thank you so much for your example, I completely agree with your approach.

As for the integration test you mentioned, I’m still unsure how to write it properly. I attempted to write a test case myself, but I’m not certain if it’s correct. Could you kindly review it and provide some suggestions? I would really appreciate your help! Here’s the test code I’ve written, where I added a new It block under the Describe section:

```go
It("should report unready status for non-existent dependencies", func() {
		nonExistentDependency := "not-existing-job"
		sqlJob := mariadbv1alpha1.SqlJob{
			ObjectMeta: metav1.ObjectMeta{
				Name:      "sqljob-with-non-existent-dependency",
				Namespace: testNamespace,
			},
			Spec: mariadbv1alpha1.SqlJobSpec{
				DependsOn: []mariadbv1alpha1.LocalObjectReference{
					{
						Name: nonExistentDependency,
					},
				},
				MariaDBRef: mariadbv1alpha1.MariaDBRef{
					ObjectReference: mariadbv1alpha1.ObjectReference{
						Name: testMdbkey.Name,
					},
					WaitForIt: true,
				},
				Username: testUser,
				PasswordSecretKeyRef: mariadbv1alpha1.SecretKeySelector{
					LocalObjectReference: mariadbv1alpha1.LocalObjectReference{
						Name: testPwdKey.Name,
					},
					Key: testPwdSecretKey,
				},
				Database: &testDatabase,
			},
		}

		By("Creating SqlJob with non-existent dependency")
		Expect(k8sClient.Create(testCtx, &sqlJob)).To(Succeed())
		DeferCleanup(func() {
			Expect(k8sClient.Delete(testCtx, &sqlJob)).To(Succeed())
		})

		By("Expecting SqlJob to report unready status")
		Eventually(func() bool {
			var updatedSqlJob mariadbv1alpha1.SqlJob
			if err := k8sClient.Get(testCtx, client.ObjectKeyFromObject(&sqlJob), &updatedSqlJob); err != nil {
				return false
			}
			for _, condition := range updatedSqlJob.Status.Conditions {
				if condition.Type == mariadbv1alpha1.ConditionTypeComplete {
					return condition.Status == metav1.ConditionFalse &&
						condition.Reason == mariadbv1alpha1.ConditionReasonFailed &&
						condition.Message == "Dependency 'not-existing-job' not found"
				}
			}
			return false
		}, testHighTimeout, testInterval).Should(BeTrue())

		By("Expecting SqlJob to not create a Job")
		Consistently(func() bool {
			var job batchv1.Job
			err := k8sClient.Get(testCtx, client.ObjectKeyFromObject(&sqlJob), &job)
			return err != nil && apierrors.IsNotFound(err)
		}, testHighTimeout, testInterval).Should(BeTrue())
	})
```

2024-10-11 10:25 UTC, mmontes11 requested changes
Hey @am6737 ! Thanks for the changes.

Your testing approach is good, but I suggest we use gomega's [Consistently](https://pkg.go.dev/github.com/onsi/gomega#Consistently) matcher and the `IsComplete` function from the `SqlJob. See:

```go
	It("should report unready status for non-existent dependencies", func() {
		nonExistentDependency := "not-existing-job"
		sqlJob := mariadbv1alpha1.SqlJob{
			ObjectMeta: metav1.ObjectMeta{
				Name:      "sqljob-with-non-existent-dependency",
				Namespace: testNamespace,
			},
			Spec: mariadbv1alpha1.SqlJobSpec{
				DependsOn: []mariadbv1alpha1.LocalObjectReference{
					{
						Name: nonExistentDependency,
					},
				},
				MariaDBRef: mariadbv1alpha1.MariaDBRef{
					ObjectReference: mariadbv1alpha1.ObjectReference{
						Name: testMdbkey.Name,
					},
					WaitForIt: true,
				},
				Username: testUser,
				PasswordSecretKeyRef: mariadbv1alpha1.SecretKeySelector{
					LocalObjectReference: mariadbv1alpha1.LocalObjectReference{
						Name: testPwdKey.Name,
					},
					Key: testPwdSecretKey,
				},
				Database: &testDatabase,
			},
		}

		By("Creating SqlJob with non-existent dependency")
		Expect(k8sClient.Create(testCtx, &sqlJob)).To(Succeed())
		DeferCleanup(func() {
			Expect(k8sClient.Delete(testCtx, &sqlJob)).To(Succeed())
		})

		By("Expecting SqlJob to report unready status consistently")
		Consistently(func() bool {
			var updatedSqlJob mariadbv1alpha1.SqlJob
			if err := k8sClient.Get(testCtx, client.ObjectKeyFromObject(&sqlJob), &updatedSqlJob); err != nil {
				return false
			}
			return !updatedSqlJob.IsComplete()
		}, 10*time.Second, testInterval).Should(BeTrue())

		By("Expecting SqlJob to not create a Job")
		Consistently(func() bool {
			var job batchv1.Job
			err := k8sClient.Get(testCtx, client.ObjectKeyFromObject(&sqlJob), &job)
			return err != nil && apierrors.IsNotFound(err)
		}, testHighTimeout, testInterval).Should(BeTrue())
```

Let me know if this makes sense to you!

2024-10-11 11:43 UTC, am6737 commented
> Hey @am6737 ! Thanks for the changes.
> 
> Your testing approach is good, but I suggest we use gomega's [Consistently](https://pkg.go.dev/github.com/onsi/gomega#Consistently) matcher and the `IsComplete` function from the `SqlJob`. See:
> 
> ```go
> 	It("should report unready status for non-existent dependencies", func() {
> 		nonExistentDependency := "not-existing-job"
> 		sqlJob := mariadbv1alpha1.SqlJob{
> 			ObjectMeta: metav1.ObjectMeta{
> 				Name:      "sqljob-with-non-existent-dependency",
> 				Namespace: testNamespace,
> 			},
> 			Spec: mariadbv1alpha1.SqlJobSpec{
> 				DependsOn: []mariadbv1alpha1.LocalObjectReference{
> 					{
> 						Name: nonExistentDependency,
> 					},
> 				},
> 				MariaDBRef: mariadbv1alpha1.MariaDBRef{
> 					ObjectReference: mariadbv1alpha1.ObjectReference{
> 						Name: testMdbkey.Name,
> 					},
> 					WaitForIt: true,
> 				},
> 				Username: testUser,
> 				PasswordSecretKeyRef: mariadbv1alpha1.SecretKeySelector{
> 					LocalObjectReference: mariadbv1alpha1.LocalObjectReference{
> 						Name: testPwdKey.Name,
> 					},
> 					Key: testPwdSecretKey,
> 				},
> 				Database: &testDatabase,
> 			},
> 		}
> 
> 		By("Creating SqlJob with non-existent dependency")
> 		Expect(k8sClient.Create(testCtx, &sqlJob)).To(Succeed())
> 		DeferCleanup(func() {
> 			Expect(k8sClient.Delete(testCtx, &sqlJob)).To(Succeed())
> 		})
> 
> 		By("Expecting SqlJob to report unready status consistently")
> 		Consistently(func() bool {
> 			var updatedSqlJob mariadbv1alpha1.SqlJob
> 			if err := k8sClient.Get(testCtx, client.ObjectKeyFromObject(&sqlJob), &updatedSqlJob); err != nil {
> 				return false
> 			}
> 			return !updatedSqlJob.IsComplete()
> 		}, 10*time.Second, testInterval).Should(BeTrue())
> 
> 		By("Expecting SqlJob to not create a Job")
> 		Consistently(func() bool {
> 			var job batchv1.Job
> 			err := k8sClient.Get(testCtx, client.ObjectKeyFromObject(&sqlJob), &job)
> 			return err != nil && apierrors.IsNotFound(err)
> 		}, 10*time.Second, testInterval).Should(BeTrue())
> ```
> 
> Please, note that I have updated the timeout for `Consistenly`, ensuring the state for `10s` should be enough. Otherwise we would be making assertions during `5m` (`testHighTimeout`).
> 
> Let me know if this makes sense to you!

Thanks for the feedback! I'll go ahead and update the test accordingly with the changes you suggested.

Your input is really helpful, I appreciate it!

2024-10-11 11:44 UTC, mmontes11 requested changes

2024-10-11 11:44 UTC, mmontes11 commented on internal/controller/sqljob_controller.go
> +			return false, ctrl.Result{}, err
This is no longer needed, see the suggested solution here:
https://github.com/mariadb-operator/mariadb-operator/pull/924#pullrequestreview-2362478989

2024-10-11 14:25 UTC, mmontes11 requested changes
LGTM! Please fix the linting and rebase with `main`. Then we can merge,

2024-10-11 17:42 UTC, mmontes11 approved these changes
LGTM! 🚀 Thanks a lot for this contribution @am6737 🙇🏻

2024-10-11 17:43 UTC, merged