Perform proper switchover before updating master in semi-sync replication
mariadb-operator/mariadb-operator pull request #967
Opened 2024-10-26 08:59 UTC by hedgieinsocks

Hello again! This PR continues efforts made in https://github.com/mariadb-operator/mariadb-operator/pull/947
Now, when we have 1) allowed switchover during statefulset update and 2) ensured that restarted replicas are configured, we can actually trigger proper switchover instead of brute force master deletion. 

This seems to be working as designed. If you find the idea valid, please feel free to edit and modify it as you see fit to bring it to the project's standards and your vision.

P.S. Since the switchover logic includes a configurable sync timeout, I did not inject a hardcoded sleep step here. But perhaps we should add it anyway cause if e.g. automatic failover is disabled, we nuke the master right after the replicas that could be not yet synced, and thus risk getting into big trouble.

2024-10-29 17:55 UTC, mmontes11 requested changes
Thanks for raising this @hedgieinsocks ! The approach looks legit to me, I've left a comment suggesting to standarize the mechanism to skip a reconciliation step, also used in https://github.com/mariadb-operator/mariadb-operator/pull/947. Let me know what you think.

> P.S. Since the switchover logic includes a configurable sync timeout,

I'm not quite convinced with this bit of the switchover, that's one of the reasons why we say that replication is alpha. We should come up with a more efficient switchover strategy and avoid imitating the current one, as it is not ideal. Some thoughts:
- Monitor the lag of every replica and track it in the status
- Define a lag threshold to define a replica that would be "suitable to be promoted" as primary
- In switchover/failover scenarios, evaluate the "suitable to be promoted" replicas and choose the one with less lag (and maybe evaluate other parameters as well)
- We could optionally introduce a delay here if needed, because we have more certainty that the "suitable to be promoted" replicas will sync in a reasonable time. 

Our candidate replicas are all the ready Pods right now, something that is sub-optimal, as the readiness of the Pods don't depend on the replication lag, it is just a `SELECT 1;` which has no guarantees in terms of replication.

2024-10-30 09:04 UTC, hedgieinsocks commented on internal/controller/mariadb_controller.go
> +	if errors.Is(err, mariadbv1alpha1.ErrPrimarySwitchoverRequired) {
Makes perfect sense to me :+1:

2024-10-30 09:10 UTC, hedgieinsocks commented on internal/controller/mariadb_controller_update.go
> +	if mariadb.IsMaxScaleEnabled() || mariadb.IsRestoringBackup() {
Yes, let it be handled in a separate pr :+1:

2024-10-30 09:27 UTC, hedgieinsocks commented
> In switchover/failover scenarios, evaluate the "suitable to be promoted" replicas and choose the one with less lag (and maybe evaluate other parameters as well)

Yes, since we already have a list of replicas at hand, I wanted to loop over them right after replication is configured, to check that `Seconds_Behind_Master` is below e.g. 10 seconds and if it fits, return the index of that pod. And if none of the replicas is within this 10 seconds limit, just requeue in 1 second.

My idea was to create a function like [this](https://github.com/mariadb-operator/mariadb-operator/blob/76066c4d2cfebd0d15a8771464bb4c61148b82e5/pkg/sql/sql.go#L544-L551) one. But it turned out that `SHOW REPLICA STATUS` cannot be easily filtered and `row.Scan()` must be fed with the whole huge type we will have to create from https://mariadb.com/kb/en/show-replica-status/. I thought well, this is ugly but looks doable. However, the linked doc says: _The order in which the columns appear depends on the MariaDB version._ So I'm afraid we will have to retrieve column names and jump into some hoops there. And I kinda lack golang experience and skill to do this properly, so I decided to move in small steps and do what I can do for now.

2024-10-30 10:48 UTC, mmontes11 commented on internal/controller/mariadb_controller_update.go
> +	if mariadb.IsMaxScaleEnabled() || mariadb.IsRestoringBackup() {
Great. In addition, since the switchover is handled by MaxScale we will need to wait until MaxScale finishes the operation

2024-10-30 11:14 UTC, mmontes11 approved these changes
LGTM! 🚀 Thanks for the contribution and the refactor @hedgieinsocks 🦔 !

> Yes, since we already have a list of replicas at hand, I wanted to loop over them right after replication is configured, to check that Seconds_Behind_Master is below e.g. 10 seconds and if it fits, return the index of that pod. And if none of the replicas is within this 10 seconds limit, just requeue in 1 second.

Right, instead of tracking the status as I previously mention, we could replace the `HealthyMariaDBReplica` function with this suggestion, seems a more natural step forward. This way we also ensure that the lag is up to date.

> My idea was to create a function like [this](https://github.com/mariadb-operator/mariadb-operator/blob/76066c4d2cfebd0d15a8771464bb4c61148b82e5/pkg/sql/sql.go#L544-L551) one. But it turned out that SHOW REPLICA STATUS cannot be easily filtered and row.Scan() must be fed with the whole huge type we will have to create from https://mariadb.com/kb/en/show-replica-status/. I thought well, this is ugly but looks doable. However, the linked doc says: The order in which the columns appear depends on the MariaDB version. So I'm afraid we will have to retrieve column names and jump into some hoops there. And I kinda lack golang experience and skill to do this properly, so I decided to move in small steps and do what I can do for now.

Yeah, parsing `SHOW REPLICA STATUS` doesn't seem trivial and could potentially cause problems given that we need to support MariaDB 10.5+.

Maybe a more structured and predictable approach could be querying a system table, something like:

```go
// getReplicaLagFromPerformanceSchema is a ChatGPT generated function to give you a very rough idea of how to get the lag of a given replica. Btw, channelName will be "mariadb-operator" always
func getReplicaLagFromPerformanceSchemaByWorker(db *sql.DB, channelName string, workerID int) (time.Duration, error) {
	query := `
		SELECT 
			UNIX_TIMESTAMP(NOW()) - UNIX_TIMESTAMP(LAST_APPLIED_TRANSACTION_ORIGINAL_COMMIT_TIMESTAMP)
		FROM 
			performance_schema.replication_applier_status_by_worker 
		WHERE 
			CHANNEL_NAME = ? AND WORKER_ID = ?
		LIMIT 1;
	`

	var lagSeconds sql.NullInt64
	err := db.QueryRow(query, channelName, workerID).Scan(&lagSeconds)
	if err != nil {
		return 0, err
	}

	if !lagSeconds.Valid {
		return 0, fmt.Errorf("no replication data available for channel: %s and worker ID: %d", channelName, workerID)
	}

	return time.Duration(lagSeconds.Int64) * time.Second, nil
}
```
This could be added to [pkg/sql](https://github.com/mariadb-operator/mariadb-operator/tree/main/pkg/sql) as you proposed.

Let's move the switchover discussion to an issue if you don't mind,

2024-10-30 11:17 UTC, merged

2024-11-18 17:40 UTC, mariadb-pieterhumphrey commented
Hi @hedgieinsocks I was wondering if you'd like to join our private operator beta program. 
please email me at pieter dot humphrey at mariadb.com if you would like to discuss this.